### ISSUE TITLE
fps limiter

### ISSUE THREAD

**Issue by mechanics-bane** [Lazerbeak12345/pixelmanipulator#42]
add an fps limiter to make the frames smother (and so you can have a small canvas and still see what is happening)

**Comment by mechanics-bane** [comment]
hi nathan

**Comment by Lazerbeak12345** [comment]
i lost the game

**Comment by mechanics-bane** [comment]
i lost the game

**Comment by Lazerbeak12345** [comment]
Related to #19 (which might resolve this issue)

**Comment by mechanics-bane** [comment]
can you post the link to the one with customize button?

**Comment by Lazerbeak12345** [comment]
You mean the version of the project that has the customize thing? That'd be in pull request #37. Unfortunately, as it's not yet released, the only way to run that is do download the repo on your own computer and host it there (this is how I test it). (or else to wait for that PR to be merged, as it likely is going to be)

**Comment by mechanics-bane** [comment]
i am talking about the link that you used

**Comment by mechanics-bane** [comment]
i cant host it on a crome book

**Comment by mechanics-bane** [comment]
this is isaac by the way

**Comment by mechanics-bane** [comment]
ok

**Comment by mechanics-bane** [comment]
it works fabulously at 700x700

**Comment by mechanics-bane** [comment]
have you added arrow keys to move the view box yet

**Comment by mechanics-bane** [comment]
you should add an element that when it gets power(wire world) it disappears

**Comment by Lazerbeak12345** [comment]
Fun fact #19 actually made things harder.... yayyyyyyyyyyyyyyyy

**Comment by Lazerbeak12345** [comment]
Fixed in [5.5.0](https://github.com/Lazerbeak12345/pixelmanipulator/releases/tag/5.5.0)
